// auth
export const LOAD_USER_PENDING = "LOAD_USER_PENDING";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const REGISTER_PENDING = "REGISTER_PENDING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// stats
export const FETCH_STATS_PENDING = "FETCH_STATS_PENDING";
export const FETCH_STATS_SUCCESS = "FETCH_STATS_SUCCESS";
export const FETCH_STATS_FAILURE = "FETCH_STATS_FAILURE";
export const UPDATE_STATS_PENDING = "UPDATE_STATS_PENDING";
export const UPDATE_STATS_SUCCESS = "UPDATE_STATS_SUCCESS";
export const UPDATE_STATS_FAILURE = "UPDATE_STATS_FAILURE";

// errors
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";